language: emacs-lisp
dist: trusty
sudo: required
cache:
  - directories:  # Cache stable Emacs binaries (saves 1min per job)
      - "$HOME/emacs/"
env:
  - EMACS_VERSION=26.3
before_install:
  - export PATH="$HOME/bin:$PATH"
  - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  - make -f emacs-travis.mk install_emacs
  - make -f emacs-travis.mk install_cask
install:
  - make init
script:
  - make test

#
# Emacs
#
# Local Variables:
# indent-tabs-mode: nil
# coding: utf-8
# End:
#
