dist: trusty
language: emacs-lisp
before_install:
  - sudo mkdir /usr/local/evm
  - sudo chown travis:travis /usr/local/evm
  - export PATH="/home/travis/.cask/bin:$PATH"
  - export PATH="/home/travis/.evm/bin:$PATH"
  - curl -fsSkL https://raw.github.com/rejeep/evm/master/go | bash
  - evm install $EVM_EMACS --use
  - echo $PATH
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
env:
  - EVM_EMACS=emacs-26.2-travis
script:
  - emacs --version
  - make test
branches:
  only:
    - master

#
# Emacs
#
# Local Variables:
# indent-tabs-mode: nil
# coding: utf-8
# End:
#
