dist: trusty
language: emacs-lisp
env:
  - EVM_EMACS=emacs-26.3-travis
before_install:
  - sudo mkdir /usr/local/evm
  - sudo chown travis:travis /usr/local/evm
  - export PATH="/home/travis/.cask/bin:$PATH"
  - export PATH="/home/travis/.evm/bin:$PATH"
  - curl -fsSkL https://raw.github.com/rejeep/evm/master/go | bash
  - evm install $EVM_EMACS --use
  - ln -s /usr/local/evm/$EVM_EMACS /tmp/$EVM_EMACS
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - cask install
script:
  - emacs --version
  - make testsrc
branches:
  only:
    - master

#
# Emacs
#
# Local Variables:
# indent-tabs-mode: nil
# coding: utf-8
# End:
#
