language: emacs-lisp
dist: trusty
sudo: required
cache:
  - directories:
      # Cache stable Emacs binaries (saves 1min per job)
      - "$HOME/emacs/"
matrix:
  fast_finish: true
env:
  - EMACS_VERSION=27.1
  - EMACS_VERSION=snapshot
before_install:
  - export PATH="$HOME/bin:$PATH"
  - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  - make -f emacs-travis.mk install_emacs
  - make -f emacs-travis.mk install_gnutls
  - make -f emacs-travis.mk install_cask
  - make -f emacs-travis.mk install_texinfo
install:
  - make init
script:
  - make test

#
# Emacs
#
# Local Variables:
# indent-tabs-mode: nil
# coding: utf-8
# End:
#
