(source gnu)
(source melpa)

(package-file "org-glance.el")

(development
 (depends-on "aes")
 (depends-on "cl")
 (depends-on "cl-generic")
 (depends-on "cl-lib")
 (depends-on "dash")
 (depends-on "dash-functional")
 (depends-on "ert")
 (depends-on "ert-runner")
 (depends-on "f")
 (depends-on "load-relative")
 (depends-on "seq")
 (depends-on "undercover")
 (depends-on "ledger-mode")
 (depends-on "ts")
 (depends-on "with-simulated-input"))
