(source gnu)
(source melpa)
(source org)
(source marmalade)

(package-file "org-glance.el")

(depends-on "aes")
(depends-on "cl-generic")
(depends-on "cl-lib")
(depends-on "dash")
(depends-on "eieio")
(depends-on "eieio-core")
(depends-on "f")
(depends-on "ledger-mode")
(depends-on "load-relative")
(depends-on "s")
(depends-on "seq")
(depends-on "transient")
(depends-on "ts")

(development
 (depends-on "ert")
 (depends-on "ert-runner")
 (depends-on "ert-async")
 (depends-on "with-simulated-input")
 (depends-on "undercover"))
