(package "org-glance" "0.0.1" "Org-mode mindmap.")

(website-url "https://github.com/rails-to-cosmos/org-glance")
(keywords "org-mode" "graph" "mindmap")

(package-file "org-glance.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")
(source "org")

(depends-on "emacs" "29.1")
(depends-on "org")
(depends-on "aes")
(depends-on "dash")
(depends-on "f")
(depends-on "ht")
(depends-on "highlight")
(depends-on "transient")
(depends-on "elsa")
